#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Estimotes.Droid.Resource", IsApplication=true)]

namespace Estimotes.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int beacon_blueberry = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beacon_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beacon_icy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_distance = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dot = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int device_list = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int dot = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int refresh = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int root = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int sonar = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int status = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar_indeterminate_progress = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int distance_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notify_demo = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int scan_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
