require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "estimotesdk-1.0.4.2”

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do

	formatted_date = Date.today.strftime("%Y%m%d")
	package_name = COMPONENT + "." + formatted_date

	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{package_name}.xam \
		--name="EstimoteSDK" \
		--summary="Estimote SDK for Xamarin.Android. A binding for the Estimote SDK for Android. (Preview)" \
		--publisher="Tom Opgenorth" \
		--website="https://github.com/topgenorth/Estimotes-Xamarin" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/estimotesdk_128x128.png" \
		--icon="icons/estimotesdk_512x512.png" \
		--library="android":"bin/EstimotesBinding.dll" \
		--sample="EstimoteSDK. Sample project demonstrating the Estimote SDK in Xamarin.Android":"samples/EstimotesSample.sln"
		END
	puts "* Creating #{package_name}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{package_name}"
end
